language: php
php:
  - '7.1'
env:
  - DB=mysql
before_script:
    - composer install 
    - mysql -u root -e 'CREATE DATABASE test;'
    - mysql -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';"
    - mysql -u root -e "GRANT ALL ON test.* TO 'test'@'localhost';"
addons:
  mariadb: '10.2'
