language: php
php:
  - '7.1'
env:
  - DB=mysql
before_script:
    - composer install
    - echo "USE mysql;\nUPDATE user SET password=PASSWORD('secret') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
addons:
  mariadb: '10.2'
